# Generated by Django 4.2.5 on 2023-10-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Customer', 'Customer'), ('Driver', 'Driver'), ('Warehouse Manager', 'Warehouse Manager')], default='Customer', max_length=80),
        ),
    ]
