# Generated by Django 4.2.5 on 2023-11-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agreed_to_supplied',
        ),
    ]
