# Generated by Django 4.1.6 on 2023-11-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_location',
            field=models.CharField(default='Airport Round About', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(default='FBazaar', max_length=100, unique=True),
        ),
    ]
