# Generated by Django 4.1.6 on 2023-11-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.CharField(blank=True, default='FBazaar', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='store_location',
            field=models.CharField(blank=True, default='Airport Round About', max_length=100),
        ),
    ]
