# Generated by Django 4.2.5 on 2023-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_supplied',
            field=models.BooleanField(default=False),
        ),
    ]
