# Generated by Django 4.2.5 on 2023-10-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
