# Generated by Django 4.1.6 on 2023-11-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToPriceChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('date_rated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyAboutItemRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejected', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyAboutItemVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Water', 'Water'), ('Drinks', 'Drinks')], default='Water', max_length=80)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='Small', max_length=30)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('picture', models.ImageField(blank=True, upload_to='store_items')),
                ('volume', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('exclusive', models.BooleanField(default=False)),
                ('promotion', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('quantity_qualify_for_free_delivery', models.IntegerField(default=20)),
                ('quantity_needed_for_wholesale_price', models.IntegerField(default=20)),
                ('item_verified', models.BooleanField(default=False)),
                ('item_rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
