# Generated by Django 4.2.5 on 2023-10-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='price',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='quantity_needed_for_wholesale_price',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='quantity_qualify_for_free_delivery',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='picture',
            field=models.ImageField(upload_to='store_items'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='Small', max_length=30),
        ),
        migrations.CreateModel(
            name='ItemRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_api.storeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_making_remarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddToPriceChanged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_api.storeitem')),
            ],
        ),
    ]
