# Generated by Django 4.2.5 on 2023-11-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='item_verified',
            field=models.BooleanField(default=False),
        ),
    ]
