# Generated by Django 4.1.6 on 2023-12-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Drinks', 'Drinks'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Beauty & Saloon', 'Beauty & Saloon'), ('Office', 'Office')], default='Water', max_length=80),
        ),
    ]
