# Generated by Django 4.2.5 on 2023-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_remove_storeitem_price_storeitem_new_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
