# Generated by Django 4.1.6 on 2023-11-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
        ('store_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='company_name',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registered_stores', to='stores.registerstore'),
        ),
    ]
