# Generated by Django 4.2.5 on 2023-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_alter_storeitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='picture',
            field=models.ImageField(blank=True, upload_to='store_items'),
        ),
    ]
