# Generated by Django 4.1.6 on 2023-11-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_notifyaboutitemverified_notifyaboutitemrejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Drinks', 'Drinks')], default='Water', max_length=80),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
