# Generated by Django 4.2.5 on 2023-10-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_alter_storeitem_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
