# Generated by Django 4.1.6 on 2023-11-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0004_alter_storeitem_category_alter_storeitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='item_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
