# Generated by Django 4.2.5 on 2023-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0007_storeitem_exclusive_storeitem_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemremarks',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
