# Generated by Django 4.2.5 on 2023-10-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0008_itemremarks_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
