# Generated by Django 4.1.6 on 2023-11-10 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordered', '0001_initial'),
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_being_ordered', to='store_api.storeitem'),
        ),
    ]
