# Generated by Django 4.2.5 on 2023-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
