# Generated by Django 4.2.5 on 2023-10-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_clearedpickups_order_item_and_more'),
        ('cart', '0004_remove_cart_item_cart_ordered_cart_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_item', to='orders.orderitem'),
        ),
    ]
