# Generated by Django 4.2.5 on 2023-10-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_item'),
        ('cart', '0005_alter_cart_ordered_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordering_item', to='orders.orderitem'),
        ),
    ]
