# Generated by Django 4.2.5 on 2023-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearedPickUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsDroppedOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPickedUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Water', 'Water'), ('Drinks', 'Drinks')], default='Water', max_length=80)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='Small', max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('payment_method', models.CharField(choices=[('Mobile Money', 'Mobile Money'), ('Cash On Delivery', 'Cash On Delivery')], default='Cash On Delivery', max_length=80)),
                ('drop_off_location_lat', models.CharField(blank=True, max_length=255)),
                ('drop_off_location_lng', models.CharField(blank=True, max_length=255)),
                ('date_order_created', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=70)),
                ('delivery_method', models.CharField(default='Delivery', max_length=50)),
                ('ordered', models.BooleanField(default=False)),
                ('unique_order_code', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QualifiedForBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
