# Generated by Django 4.2.5 on 2023-10-21 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualifiedforbonuses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchasing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemspickedup',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='itemspickedup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_house_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsdroppedoff',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='itemsdroppedoff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clearedpickups',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
    ]
