# Generated by Django 4.2.5 on 2023-10-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='drop_off_location',
            new_name='drop_off_location_lat',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drop_off_location_lng',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
