# Generated by Django 4.2.5 on 2023-10-25 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_orderitem_order_status_itemsintransit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='assigned_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_assigned_to_deliver_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
