# Generated by Django 4.2.5 on 2023-10-17 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_quantity'),
        ('orders', '0005_remove_orderitem_item_dropped_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unique_order_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
