# Generated by Django 4.2.5 on 2023-10-31 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_initial'),
        ('orders', '0008_alter_orderitem_assigned_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearedpickups',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='driverscurrentlocation',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverscurrentlocation',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='driverscurrentlocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemsdroppedoff',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='itemsdroppedoff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itemsintransit',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='itemsintransit',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='itemspickedup',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='itemspickedup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qualifiedforbonuses',
            name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_order_created',
            new_name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='assigned_driver',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='drop_off_location_lat',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='drop_off_location_lng',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unique_order_code',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store_api.storeitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='AssignDriverToOrder',
        ),
        migrations.DeleteModel(
            name='ClearedPickUps',
        ),
        migrations.DeleteModel(
            name='DriversCurrentLocation',
        ),
        migrations.DeleteModel(
            name='ItemsDroppedOff',
        ),
        migrations.DeleteModel(
            name='ItemsInTransit',
        ),
        migrations.DeleteModel(
            name='ItemsPickedUp',
        ),
        migrations.DeleteModel(
            name='QualifiedForBonuses',
        ),
    ]
