# Generated by Django 4.1.6 on 2023-11-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_driver',
        ),
    ]
