# Generated by Django 4.1.6 on 2023-11-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsintransit',
            name='pass_in_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingorders',
            name='pass_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingorders',
            name='pass_processing',
            field=models.BooleanField(default=False),
        ),
    ]
