# Generated by Django 4.2.5 on 2023-11-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_order_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
