# Generated by Django 4.1.6 on 2023-11-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingorders',
            name='user',
        ),
    ]
